label skibidiohiorizzgyatt:
    stop music fadeout 1.0
    scene bg residential_day
    with dissolve_scene_full
    "..."
    "It's a bright Ohio morning like any other."
    "Today is Hawk Tuahsday, the second day of the week, and it already feels like this week fell off."
    "The Skibidi Toilets are destroying the downtown area, Baby Gronk is broadcasting his latest Rizz King news, and I'm walking to school."
    mc "Man, this is so not sigma."
    mc "I'm starving. Wish I had a Lunchly with some Prime right about now."
    "Sometimes, I wish I didn't have to pay the daily Fanum Tax."
    "Who does all of this food even go to, anyways? Kai Cenat? Adin Ross?"
    "...Maybe Mr. Beast takes it and gives it to the children in Africa?"
    "...Nah, I doubt it.{w} Would be nice to know my yummers food was going to somewhere important, though."
    mc "Man...I think Monday left me broken..."
    s "GYATTTT!!!"
    mc "What the sigma??"
    "All of a sudden, an insane girl starts running towards me from across the street, distracting me from my mewing."
    "She continues charging, and quickly reaches me, tackling me with the force of a titan cameraman."
    mc "AAAHHH!"
    s "[player], it's you! I barely recognized you with all of that insane rizz!"
    ".........huh?"
    "Is this girl talking to me? I don't think I've ever had a successful pull in my life."
    "Wait a hot minute...{w} is that..."
    mc "Sayori?!"
    s "Uh, duh!? Did you forget me after all these years?"
    s "It's been so long since I've seen your lovely gyatt!"
    "Sayori used to be my best friend as a child."
    "We were TikTok friends, Snapchat besties, and even YouTube community post partners in crime."
    "But something happened one day that drove us away..."
    "Honestly, I forgor what exactly it was, though."
    "Either way, it's been a fat minute since I saw her."
    "But now... {i}she mogs the other girls I've seen lately.{/i}."
    mc "Sayori... you look so fucking sigma right now."
    s "Eeehh?!"
    "Sayori blushes and pushes me away."
    s "Y-you can't just yap things like that!"
    mc "Ah- did I say that out loud? I'm so cooked..."
    s "Uh, yeah? You can be such a beta sometimes, [player]."
    "Damn...this is why I'm not a rizzler.{w} Me and my stupid mouth."
    mc "Ah- sorry, Sayori. You just... look a bit glowed up from the last time I met you."
    s "Well, of course I do, blud~"
    s "I've been looksmaxxing for months now; I've gone from a Hoikaido 7 to a Tokyo 8!"
    mc "That's amazing, Sayori! I always knew you would pop off someday."
    mc "I even remember making a promise to you that I would never unsubscribe from believing in you."
    s "Oh, [player], that's so based and memorypilled of you!"
    s "I'm glad you still remember the reels we made together."
    mc "Of course, Sayori; they're still in my digital footprint."
    sk "....yes yes yes!"
    "Huh? What was that?"
    sk "Mmm, skibidi dop dop dop yes yes!"
    extend "\ SKIBIDI SKIBIDI SKIBIDI!"
    "Oh, fuck!"
    "A Dark Grey Semi-Medium Skibidi!"
    mc "Run, Sayori!"
    sk "DOP DOP DOP YES YES! SKIBIDI SKIBIDI SKIBIDI!"
    s "AAAAAAAAAAAA-{w=1}{nw}"
    "Sayori screams at the top of her lungs, and starts just absolutely BOLTING down the street...{i}towards{/i} the Skibidi Toilet?!"
    mc "Sayori, wait!"
    "Not hearing me, or maybe simply not caring, Sayori continues to run full speed at the Skibidi."
    "Luckily, this one isn't equipped with any weapons... but its neck still extends out, reaching towards my old best friend."
    mc "NOOOOOOOOO!"
    "I close my eyes, bracing for the sound of the telltale {i}crunch{/i} that comes when a Skibidi chomps someone..."
    "But it doesn't arrive."
    "Slowly, I peek open my eyes."
    ##play audio flush
    "What?!"
    "Looking back at the street, I see Sayori standing atop the back of the toilet, triumphantly holding the pull-up handle that marks a Skibidi's weak point."
    mc "Holy shit..."
    "Did Sayori just do that?"
    s "Sorry about that, ehehe~"
    "She hops down from the toilet, tossing the handle to the side as she walks back towards me."
    mc "Say-{w} I-{w} what?!"
    s "Well? Aren't you going to thank me, [player]?"
    mc "Sayori, that was..."
    extend "{w} the most bussin thing I've ever seen, no cap."
    "I'm not lying. She may be cheugy, but that moment will be living rent free in my head for the rest of time."
    mc "How did you-{w=1}{nw}"
    mc "Where did you learn how to bust it down like that?!"
    "This is going to be my Roman Empire for the next few months; I can already tell."
    s "Nowhere. Just put the fries in the bag."
    mc "What do you mean?! You just took out that mfer like he was nothing!"
    s "Seriously, [player], pipe down pookie!"
    s "There's more of them close-by..."
    s "And they're a bunch of meanies!"
    "She still {i}sounds{/i} like Sayori, at least. {w}But what exactly has she been doing these past few months? Where was bro training?"
    mc "Shouldn't we run then? I definitely am not goated with the sauce like you..."
    s "Skills? Ehehehe.... I don't have skills, lil' bro."
    mc "You're widdewawy-{w} never mind. Let's just get out of here."
    s "Okay... I guess I'll see you at school, then, homeboy?"
    mc "....You're capping me."
    mc "We still have to go to school with this terrorism thing going on? With all of the Skibidi Toilets??"
    s "Yep!"
    mc "...Of course. Never a break from school, unless all of the teachers and staff have been unalived, or something."
    s "Follow me, I know a goated shortcut!"
    "Reluctantly, I follow Sayori down a side street, looking over my shoulder at the fallen Skibidi in the middle of the road."
    "Honestly, it gives me the ick."
    #bg transition
    mc "Erm, Sayori..."
    s "Yeah?"
    "Man, her head sure is empty. No thoughts in there."
    mc "I know that you'd be pretty poggers at fighting... {w}{i}apparently{/i}..."
    mc "But, things could get really goofy ahh if you draw attention to us like that!"
    mc "I heard that the toilets can sense fallen allies, and then we'll get killed by a whole hoard of flying Skibidi tanks!"
    s "Nah, I'd win."
    mc "You widdewawy would not, Sayori."
    s "Nah.... I'd win."
    mc "Stop yapping!"
    s "But [player]... I'm Kagurabaching! Meanie..."
    mc "..."
    "Of course getting hot would have made Sayori lose her mind...."
    "I guess personality really is the hardest thing to come by."
    "I really should meet some other people one of these days, but that won't work with my rizz levels so low."
    mc "Just help me get to school, Sayori."
    s "You got it! Should be pretty easy as long as we take the train."
    mc "There's a train that goes to the school?"
    mc "..."
    mc "What's it training for?"
    #very disappointed sigh
    s "Shut the hell up and follow me."
    #fade
    "Sayori takes me into the side of a building marked \"FNAF Lore\", which leads to a set of stairs that descend for quite a while."
    mc "Uh...Sayori? Are you sure this is a train station? Looks more like the backrooms."
    s "Not so loud, [player]...it's a bit of a secret, so be chalant, ehehe~"
    s "Plus, if you awaken Freddy Five Bear, you might get the Bite of '87!"
    mc "....Yeah, sure. That's a real thing here. Whatever. There better be free wifi down here..."
    s "Nope! Just a bunch of gooners!"
    "..."
    "I really hope I don't see any edging on the way to school; I'd rather see that in the safety of my own home."
    "Sayori continues to lead me down a few passageways; the air is damp and moist, which reminds me of how much I hate the word 'moist'."
    s "Just a bit more...I think."
    mc "What do you mean, you think?"
    s "Well, I haven't gone here before, and my phone doesn't have data to check the TikTok that told me about this."
    "..."
    mc "You took me into a random abandoned building based off of a random TikTok!?!?"
    mc "Are you insane?!"
    mc "We're gonna get kidnapped, or robbed, or killed, or-{w=1}{nw}"
    s "Re{i}lax{/i}, we're fine. I'll protect you if you're gonna be such a baby about it~"