label skibidiohiorizzgyatt:
    stop music fadeout 1.0
    scene bg residential_day
    with dissolve_scene_full
    "..."
    "It's a bright Ohio morning like any other."
    "The Skibidi Toilets are destroying the downtown area, Baby Gronk is broadcasting his latest Rizz King news, and I'm walking to school."
    mc "Man, this sucks."
    mc "I'm starving."
    "Sometimes, I wish I didn't have to pay the daily Fanum Tax."
    "Who does all of this food even go to, anyways?"
    "Kai Cenat? Adin Ross?"
    "...Maybe Mr. Beast takes it and gives it to the children in Africa?"
    "...Nah, I doubt it.{w} Would be nice to know my food was going to somewhere important, though."
    mc "Man...my life is so uneventful..."
    s "GYATTTT!!!"
    mc "What the hell?"
    "All of a sudden, an insane girl starts running towards me from across the street, distracting me from my mewing."
    mc "AAAHHH!"
    s "[player], it's you! I barely recognized you with all of that insane rizz!"
    ".........huh?"
    "Is this girl talking to me? I don't think I've ever had a successful pull in my life."
    "Wait, is that..."
    mc "Sayori?!"
    s "Uh, duh! Did you forget me after all these years?"
    s "It's been so long since I've seen your lovely gyatt!"
    "Sayori used to be my best friend as a child."
    "We were TikTok friends, Snapchat besties, and even YouTube community post partners in crime."
    "But something happened one day that drove us away..."
    "Honestly, I forgot what exactly it was, though."