label skibidiohiorizzgyatt:
    stop music fadeout 1.0
    scene bg residential_day
    with dissolve_scene_full
    "..."
    "It's a bright Ohio morning like any other."
    "The Skibidi Toilets are destroying the downtown area, Baby Gronk is broadcasting his latest Rizz King news, and I'm walking to school."
    mc "Man, this sucks."
    mc "I'm starving."
    "Sometimes, I wish I didn't have to pay the daily Fanum Tax."
    "Who does all of this food even go to, anyways?"
    "Kai Cenat? Adin Ross?"
    "...Maybe Mr. Beast takes it and gives it to the children in Africa?"
    "...Nah, I doubt it.{w} Would be nice to know my food was going to somewhere important, though."
    mc "Man...my life is so uneventful..."
    s "GYATTTT!!!"
    mc "What the hell?"
    "All of a sudden, an insane girl starts running towards me from across the street, distracting me from my mewing."
    "She continues charging, and quickly reaches me, tackling me with the force of a titan cameraman."
    mc "AAAHHH!"
    s "[player], it's you! I barely recognized you with all of that insane rizz!"
    ".........huh?"
    "Is this girl talking to me? I don't think I've ever had a successful pull in my life."
    "Wait a minute...{w} is that..."
    mc "Sayori?!"
    s "Uh, duh!? Did you forget me after all these years?"
    s "It's been so long since I've seen your lovely gyatt!"
    "Sayori used to be my best friend as a child."
    "We were TikTok friends, Snapchat besties, and even YouTube community post partners in crime."
    "But something happened one day that drove us away..."
    "Honestly, I forgot what exactly it was, though."
    "Either way, it's been a long time since I saw her."
    "But now... {i}she looks insanely hot{/i}."
    mc "Sayori... you look so fucking sigma right now."
    s "Eeehh?!"
    "Sayori blushes and pushes me away."
    s "Y-you can't just say things like that!"
    mc "Ah- did I say that out loud?"
    s "Uh, yeah? You can be such a beta sometimes, [player]."
    "Damn...this is why I'm not a rizzler.{w} Me and my stupid mouth."
    mc "Ah- sorry, Sayori. You just... look a bit different from the last time I met you."
    s "Well, of course I do, silly~"
    s "I've been looksmaxxing for months now; I've gone from a Hoikaido 7 to a Tokyo 8!"
    "I have no idea what this means."
    mc "That's amazing, Sayori! I always knew you would pop off someday."
    mc "I even remember making a promise to you that I would never unsubscribe from believing in you."
    s "Oh, [player], that's so based and memorypilled of you!"
    s "I'm glad you still remember the reels we made together."
    mc "Of course, Sayori; they're still in my camera roll."
    sk "....yes yes yes!"
    "Huh? What was that?"
    sk "Mmm, skibidi dop dop dop yes yes!"
    extend "\ SKIBIDI SKIBIDI SKIBIDI!"
    "Oh, fuck!"
    "A Dark Grey Semi-Medium Skibidi!"
    mc "Run, Sayori!"
    sk "DOP DOP DOP YES YES! SKIBIDI SKIBIDI SKIBIDI!"
    s "AAAAAAAAAAAA-{w=1}{nw}"
    "Sayori screams at the top of her lungs, and starts just absolutely BOLTING down the street...{i}towards{/i} the Skibidi Toilet?!"
    mc "Sayori, wait!"
    "Not hearing me, or maybe simply not caring, Sayori continues to run full speed at the Skibidi."
    "Luckily, this one isn't equipped with any weapons... but its neck still extends out, reaching towards my old best friend."
    mc "NOOOOOOOOO!"
    "I close my eyes, bracing for the sound of the telltale {i}crunch{/i} that comes when a Skibidi chomps someone..."
    "But it doesn't arrive."
    "Slowly, I peek open my eyes."
    #flush sound
    "What?!"
    "Looking back at the street, I see Sayori standing atop the back of the toilet, triumphantly holding the pull-up handle that marks a Skibidi's weak point."
    mc "Holy shit..."
    "Did Sayori just do that?"
    s "Sorry about that, ehehe~"
    "She hops down from the toilet, tossing the handle to the side as she walks back towards me."
    mc "Say-{w} I-{w} what?!"
    s "Well? Aren't you going to thank me, [player]?"
    mc "Sayori, that was..."
    extend "{w} the most bussin thing I've ever seen, no cap."
    "I'm not lying. She may be cheugy, but that moment will be living rent free in my head for the rest of time."
    mc "How did you-{w=1}{nw}"
    mc "Where did you learn how to do that?!"
    "This is going to be my Roman Empire for the next few months; I can already tell."